backend:
  name: git-gateway
  branch: master
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "personalInfo"
    label: "Personal Info"
    folder: "content/personalInfo"
    # identifier_field: artistName
    create: true
    fields:
      - {
          label: "Artist Name",
          name: "artistName",
          default: "Natalie Fideler",
          widget: "string",
        }
      # make into relation - { label: "Featured Quote", name: "featuredQuote", widget: 'string'}
      - { label: "Artist Bio", name: "artistBio", widget: "markdown" }
  - name: "quotes"
    label: "Quotes"
    # identifier_field: "quote"
    folder: "content/quotes"
    create: false
    fields:
      - label: "Press Quotes"
        name: "pressQuotes"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - {
              label: "Featured on Home",
              name: "featuredOnHome",
              widget: "boolean",
              required: false,
            }
          - { label: "Date", name: "date", widget: "datetime" }
  - name: "work"
    label: "Work Experience"
    folder: "content/work"
    # identifier_field: "position"
    create: true
    fields:
      - label: "Positions"
        name: "positions"
        widget: "list"
        fields:
          - { label: "Position", name: "position", widget: "string" }
          - { label: "Employer", name: "employer", widget: "string" }
          - { label: "Location", name: "location", widget: "map" }
          - { label: "Start Date", name: "startDate", widget: "datetime" }
          - {
              label: "End Date",
              name: "endDate",
              widget: "datetime",
              required: false,
            }
          - {
              label: "Current",
              name: "current",
              default: false,
              widget: "boolean",
            }
  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    fields:
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
