backend:
  name: git-gateway
  branch: master
media_folder: public/images/uploads
public_folder: /images/uploads
logo_url: https://nataliefideler.netlify.com/images/uploads/NFIDELERBANNER.png
collections:
  - name: "personalInfo"
    label: "Personal Info"
    folder: "content/personalInfo"
    identifier_field: artist
    create: false
    fields:
      - { label: "Artist Name", name: "artistName", widget: "string" }
      # make into relation - { label: "Featured Quote", name: "featuredQuote", widget: 'string'}
      - { label: "Artist Bio", name: "artistBio", widget: "markdown" }
      - { label: "Artist", name: "artist", widget: hidden, default: "Artist" }
  - name: "quotes"
    label: "Quotes"
    identifier_field: "press"
    folder: "content/quotes"
    create: false
    fields:
      - label: "Press Quotes"
        name: "pressQuotes"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - {
              label: "Featured on Home",
              name: "featuredOnHome",
              widget: "boolean",
              required: false,
            }
          - {
              label: "Date",
              name: "date",
              widget: "datetime",
              dateFormat: "DD.MM.YYYY",
              timeFormat: false,
            }
      - { label: "Press", name: "press", widget: "hidden", default: "Press" }
  - name: "work"
    label: "Work Experience"
    folder: "content/work"
    identifier_field: "myWorkPage"
    create: false
    fields:
      - label: "Positions"
        name: "positions"
        widget: "list"
        fields:
          - { label: "Position", name: "position", widget: "string" }
          - { label: "Employer", name: "employer", widget: "string" }
          - {
              label: "Location",
              name: "location",
              widget: "map",
              required: false,
            }
          - {
              label: "Start Date",
              name: "startDate",
              widget: "datetime",
              dateFormat: "MM.YYYY",
              timeFormat: false,
            }
          - {
              label: "End Date",
              name: "endDate",
              widget: "datetime",
              required: false,
              dateFormat: "MM.YYYY",
              timeFormat: false,
            }
          - {
              label: "Current",
              name: "current",
              default: false,
              widget: "boolean",
            }
          - {
              label: "Description",
              name: "positionDescription",
              widget: "markdown",
              required: false,
            }
      - {
          label: "My Work Page",
          name: "myWorkPage",
          widget: "hidden",
          default: "My Work Page",
        }
  - name: "photos"
    label: "Photos"
    identifier_field: "photoPage"
    folder: "content/photos"
    create: false
    fields:
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - { label: "Image Alt", name: "imageAlt", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Photo Page",
          name: "photoPage",
          widget: "hidden",
          default: "Photo Page",
        }
